main_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
	path('admin/', admin.site.urls),
	path('products/', include('products.urls', namespace='products')),
    path('', include('products.urls', namespace='products')),
]

# urlpatterns = [
# 	path('i18n/ ', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
# ]

# urlpatterns += i18n_patterns(
#     path('products/', include('products.urls', namespace='products')),
# )

products/urls.py
from django.conf.urls import url
from . import views

app_name = 'products'
urlpatterns = [
    url(r'^$', views.ProductList.as_view(), name='list'),
    url(r'^new/$', views.ProductCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.ProductDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.ProductUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.ProductDelete.as_view(), name='delete'),
]

products/models.py
from django.urls import reverse
from django.db import models


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    display_name = models.CharField(max_length=255)
    sku = models.CharField(max_length=255)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('products:detail', args=[str(self.id)])

products/forms.py
from django import forms
from .models import Product
from modeltranslation.forms import TranslationModelForm

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'display_name', 'sku')
    

products/views.py
from django.urls import reverse_lazy
from vanilla import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import ProductForm
from .models import Product

from django.utils import translation

class ProductList(ListView):
    model = Product
    paginate_by = 20

    def dispatch(self, request, *args, **kwargs):
        # translation.activate('fi')
        # request.session[translation.LANGUAGE_SESSION_KEY] = 'fi'

        if translation.LANGUAGE_SESSION_KEY in request.session:
            del request.session[translation.LANGUAGE_SESSION_KEY]

        return super(ProductList, self).dispatch(request, *args, **kwargs)


class ProductCreate(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('products:list')

    def get_form_class(self):
        """Return the form class to use."""
        print(dir(self.form_class))
        print((self.form_class.get_initial_for_field))



        return self.form_class

class ProductDetail(DetailView):
    model = Product


class ProductUpdate(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('products:list')


class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('products:list')

products/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'products:list' %}">{% trans "Product Management" %}</a>
                </div>
        
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{% url 'products:list' %}">{% trans "Home" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'products:create' %}">{% trans "Create" %}</a>
                        </li>
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            Choose language
                            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                                <input name="next" type="hidden" value="{{ redirect_to }}" >
                                <select name="language" onchange="this.form.submit()">
                                    {% get_current_language as LANGUAGE_CODE %}
                                    {% get_available_languages as LANGUAGES %}
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    {% for language in languages %}
                                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                            {{ language.name_local }} ({{ language.code }})
                                        </option>
                                    {% endfor %}
                                </select>
                            </form>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>

            <div class="container">
                <div class="container-fluid">
                    <div class="content">
                    {% block content %}
                    {% endblock %}
                    </div>    
                </div>
            </div>
            
        </nav>



        


    </body>
</html>  

products/templates/products/product_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h1>{% trans "Delete" %}</h1>
    <p>{% trans "Are you sure you want to delete?" %}</p>

    <form id="product_form" method="post" action=".">
	    {% csrf_token %}
	    <input type="submit" value="{% trans "Yes" %}" class="btn btn-primary" /> 
	    <a href="{% url 'products:list' %}" class="btn btn-danger">{% trans "No" %}</a>
    </form>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h1>{% trans "Detail" %}</h1>
    <p>{{ object.name }}</p>

    <table class="table table-bordered table-hover">
    	<tbody>
    		<tr>
    			<th>{% trans "Product Name" %}</th><td>{{object.product_name}}</td>
    		</tr>
    		<tr>
    			<th>{% trans "Display Name" %}</th><td>{{object.display_name}}</td>
    		</tr>
    		<tr>
    			<th>{% trans "SKU" %}</th><td>{{object.sku}}</td>
    		</tr>
    	</tbody>
    </table>

    <a href="{% url 'products:list' %}">{% trans "Back to List" %}</a>
{% endblock %}

products/templates/products/product_form.html
{% extends "base.html" %}

{% load i18n %}

{% load bootstrap3 %}

{% block content %}
    <h1> {% trans "Create/Update" %} </h1>
    <form id="product_form" method="post" action="." class="form">
      {% csrf_token %}
      {% bootstrap_form form layout='vertical' %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
      {% endbuttons %}
    </form>
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h1>{% trans "Listing" %}</h1>

    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>{% trans "Product Name" %}</th>
                    <th>{% trans "Display Name" %}</th>
                    <th>{% trans "SKU" %}</th>
                    <th>{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.product_name }}</td>
                        <td>{{ object.display_name }}</td>
                        <td>{{ object.sku }}</td>
                        <td>
                            <a href="{{ object.get_absolute_url }}">{% trans "Details" %}</a> |
                            <a href="{% url 'products:update' object.pk %}">{% trans "Update" %}</a> | 
                            <a href="{% url 'products:delete' object.pk %}">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                {% empty %}
                    <td>{% trans "No items." %}</td>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <ul>

    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'products:list' %}?page={{ page_obj.previous_page_number }}">{% trans "previous" %}</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'products:list' %}?page={{ page_obj.next_page_number }}">{% trans "next" %}</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}